config/routes.rb
Rails.application.routes.draw do
  resources :posts, param: :slug
  resources :waivers

  resources :texthint2s

  resources :texthints

  resources :corporates, :path => 'corporate'

  resources :bookings
  resources :about
  resources :directions
  resources :faq
  resources :busts
  resources :rooms
  root 'welcome#index'
  resources :parties
  resource :waivers
  resource :impressions
  resources :axes

  resources :heist do
    collection do
      post :checkpw
      post :playfile
      post :update_text
      post :clear_hint
      post :custom_message
      post :testing
    end
  end

  resource :waiver
  resources :nuclearpw do
    collection do
      post :checkpw
    end
  end

  resources :wizard do
    collection do
      post :checkpw
      post :playfile
      post :update_text
      post :clear_hint
      post :custom_message
      post :testing
    end
  end
  resources :nuclear do
    collection do
      post :checkpw
      post :playfile
      post :update_text
      post :clear_hint
      post :custom_message
      post :testing
    end
  end
  resources :countdown do
    collection do
      post :checkrunning
      post :starttimer
      post :pause
      post :addtime
    end
  end
  resources :heistcountdown
  resources :wizardcountdown
  resources :nuclearcountdown

  resources :leaderboard
end

app/models/booking.rb
class Booking < ActiveRecord::Base
end

app/models/day.rb
class Day < ActiveRecord::Base
end

app/models/heist.rb
class Heist < ActiveRecord::Base
	attr_accessor :pw
end

app/models/hint.rb
class Hint < ActiveRecord::Base
end

app/models/hint2.rb
class Hint2 < ActiveRecord::Base
end

app/models/post.rb
class Post < ApplicationRecord
  # before_create :set_slug 

  def to_param
    slug
  end

  # private  
	 #  def set_slug
	 #    loop do
	 #      self.slug = SecureRandom.uuid
	 #      break unless Post.where(slug: slug).exists?
	 #    end
	 #  end
end

app/models/texthint.rb
class Texthint < ActiveRecord::Base
end

app/models/texthint2.rb
class Texthint2 < ActiveRecord::Base
end

app/models/timekeeper.rb
class Timekeeper < ActiveRecord::Base
end

app/models/waiver.rb
class Waiver < ActiveRecord::Base

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/nuclearpw_controller.rb
class NuclearpwController < ApplicationController

  def index
    render layout: "countdown"
  end

  def checkpw
    @fail = false
    if params['one'] != 0.to_s
      @fail = true
    elsif params['two'] != 4.to_s
      @fail = true
    elsif params['three'] != 1.to_s
      @fail = true
    elsif params['four'] != 0.to_s
      @fail = true
    elsif params['five'] != 1.to_s
      @fail = true
    elsif params['six'] != 8.to_s
      @fail = true
    end
    render layout: "countdown"

  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/corporates_helper.rb
module CorporatesHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/texthint2s_helper.rb
module Texthint2sHelper
end

app/helpers/texthints_helper.rb
module TexthintsHelper
end

app/helpers/waivers_helper.rb
module WaiversHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/nuclearpw/checkpw.html.haml
.container
  -if @fail == false
    .white
      ="Success"
      =image_tag "steamgenerator.png"
  -else
    .white
      ="Incorrect Date - Please go BACK and reenter"
      =link_to "nuclearpw", nuclearpw_index_path

app/views/nuclearpw/index.html.haml
.container

  %br
  %br
  %br
  %br

  = form_tag checkpw_nuclearpw_index_url do
    .date.form-group
      %p
        We picked this PW to remind us of that tragic accident.  
      %p 
        Cant dwell on that though!  Lets move forward to employee orientation day!  
      .white
        Month
      = select_tag :one, options_for_select(0..9), class: 'custom-select custom-select-lg mb-3'
      = select_tag :two, options_for_select(0..9)
      .white
        Day
      = select_tag :three, options_for_select(0..9)
      = select_tag :four, options_for_select(0..9)
      .white.custom-select
        Year
      = select_tag :five, options_for_select(0..9)
      = select_tag :six, options_for_select(0..9)
    .actions
      = submit_tag 'Submit', class: "btn-warning btn"